- name: kserve
  repo-url: https://github.com/red-hat-data-services/kserve.git
  nudged-file-paths: ["config/overlays/odh/params.env"]

- name: odh-model-controller
  repo-url: https://github.com/red-hat-data-services/odh-model-controller.git
  nudged-file-paths: ["config/base/params.env", "config/base/params-vllm-rocm.env", "config/base/params-vllm-gaudi.env"]
  verify-components:
    - name: caikit-standalone-image
      onboarded-since: rhoai-2.11
    - name: vllm-image
      onboarded-since: rhoai-2.8
      image-tag: ${release}-cuda
    - name: vllm-rocm-image
      onboarded-since: rhoai-2.16
      image-tag: ${release}-rocm
    - name: vllm-gaudi-image
      onboarded-since: rhoai-2.16
      image-tag: ${release}-gaudi

- name: trustyai-service-operator
  repo-url: https://github.com/red-hat-data-services/trustyai-service-operator.git
  nudged-file-paths: ["config/overlays/rhoai/params.env"]
  verify-components:
    - name: lmes-driver-image
      onboarded-since: rhoai-2.16
    - name: lmes-pod-image
      onboarded-since: rhoai-2.16