apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: {{fbc_component}}-{{epoch}}
  namespace: rhoai-tenant
  labels:
    appstudio.openshift.io/application: rhoai-v2-19
spec:
  application: {{rhoai_application}}
  components:
    - name: {{fbc_component}}
      containerImage: {{fbc_fragment_image}}
      source:
        git:
          url: {{git_url}}
          revision: {{git_commit}}
