apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: {{fbc_component}}-{{epoch}}
  namespace: rhoai-tenant
  labels:
#    test.appstudio.openshift.io/type: override
    konflux-release-data/rbc-release-commit: {{rbc_release_commit}}
    konflux-release-data/ocp-version: {{ocp-version}}
    konflux-release-data/artifact-type: fbc
spec:
  application: {{rhoai_application}}
  components:
    - name: {{fbc_component}}
      containerImage: {{fbc_fragment_image}}
      source:
        git:
          url: {{git_url}}
          revision: {{git_commit}}
