git:
- name: odh-dashboard
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/odh-dashboard.git
- name: kubeflow
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/kubeflow.git
- name: modelmesh-serving
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/modelmesh-serving.git
- name: odh-model-controller
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/odh-model-controller.git
  ignore-files: config/base/params.env, config/base/params-vllm-rocm.env, config/base/params-vllm-gaudi.env
- name: rest-proxy
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/rest-proxy.git
- name: modelmesh
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/modelmesh.git
- name: modelmesh-runtime-adapter
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/modelmesh-runtime-adapter.git
- name: data-science-pipelines
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/data-science-pipelines.git
- name: trustyai-explainability
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/trustyai-explainability.git
- name: trustyai-service-operator
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/trustyai-service-operator.git
  ignore-files: config/overlays/rhoai/params.env
- name: data-science-pipelines-operator
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/data-science-pipelines-operator.git
  ignore-files: config/base/params.env
- name: kuberay
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/kuberay.git
- name: codeflare-operator
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/codeflare-operator.git
- name: rhods-operator
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/rhods-operator.git
  ignore-files: 'build/**,prefetched-manifests/**'
- name: kserve
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/kserve.git
  ignore-files: 'config/overlays/odh/params.env,.tekton/*'
- name: notebooks
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/notebooks.git
- name: kueue
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/kueue.git
- name: argo-workflows
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/argo-workflows.git
- name: ml-metadata
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/ml-metadata.git
- name: data-science-pipelines-tekton
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/data-science-pipelines-tekton.git
- name: training-operator
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/training-operator.git
- name: must-gather
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/must-gather.git
- name: caikit-nlp
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/caikit-nlp.git
  ignore-files: .tekton/*
- name: rhoai-additional-images
  automerge: 'no'
  repo-url: https://github.com/red-hat-data-services/rhoai-additional-images.git
- name: text-generation-inference
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/text-generation-inference.git
- name: distributed-workloads
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/distributed-workloads.git
- name: model-registry
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/model-registry.git
- name: model-registry-operator
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/model-registry-operator.git
- name: vllm
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/vllm.git
- name: vllm-gaudi
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/vllm-gaudi.git
- name: caikit-tgis-serving
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/caikit-tgis-serving.git
- name: lm-evaluation-harness
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/lm-evaluation-harness.git
  ignore-files: '.tekton/*'
