git:
- name: optima
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/rhoai-devops-optima.git
  ignore-files: newfile.txt
- name: odh-dashboard
  automerge: 'yes'
  repo-url: https://github.com/red-hat-data-services/odh-dashboard.git
#- name: kubeflow
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/kubeflow.git
#- name: modelmesh-serving
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/modelmesh-serving.git
#- name: odh-model-controller
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/odh-model-controller.git
#- name: rest-proxy
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/rest-proxy.git
#- name: modelmesh
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/modelmesh.git
#- name: modelmesh-runtime-adapter
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/modelmesh-runtime-adapter.git
#- name: data-science-pipelines
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/data-science-pipelines.git
#- name: trustyai-explainability
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/trustyai-explainability.git
#- name: trustyai-service-operator
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/trustyai-service-operator.git
#- name: data-science-pipelines-operator
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/data-science-pipelines-operator.git
#- name: kuberay
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/kuberay.git
#- name: codeflare-operator
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/codeflare-operator.git
#- name: rhods-operator
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/rhods-operator.git
#- name: kserve
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/kserve.git
#  ignore-files: config/overlays/odh/params.env
#- name: notebooks
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/notebooks.git
#- name: kueue
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/kueue.git
#- name: argo-workflows
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/argo-workflows.git
#- name: ml-metadata
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/ml-metadata.git
#- name: data-science-pipelines-tekton
#  automerge: 'yes'
#  repo-url: https://github.com/red-hat-data-services/data-science-pipelines-tekton.git
