git:
- name: opendatahub-operator
  automerge: 'no'
  src:
    url: https://github.com/opendatahub-io/opendatahub-operator.git
    branch: master
  dest:
    url: https://github.com/red-hat-data-services/opendatahub-operator.git
    branch: master
- name: odh-manifests
  automerge: 'no'
  src:
    url: https://github.com/opendatahub-io/odh-manifests.git
    branch: master
  dest:
    url: https://github.com/red-hat-data-services/odh-manifests.git
    branch: master
- name: odh-dashboard
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/odh-dashboard.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/odh-dashboard.git
    branch: main
- name: kubeflow
  automerge: 'no'
  src:
    url: https://github.com/opendatahub-io/kubeflow.git
    branch: v1.6-branch
  dest:
    url: https://github.com/red-hat-data-services/kubeflow.git
    branch: main
- name: modelmesh-serving
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/modelmesh-serving.git
    branch: release-0.11.1
  dest:
    url: https://github.com/red-hat-data-services/modelmesh-serving.git
    branch: main
- name: odh-model-controller
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/odh-model-controller.git
    branch: release-0.12.0
  dest:
    url: https://github.com/red-hat-data-services/odh-model-controller.git
    branch: main
- name: rest-proxy
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/rest-proxy.git
    branch: release-0.11.1
  dest:
    url: https://github.com/red-hat-data-services/rest-proxy.git
    branch: main
- name: modelmesh
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/modelmesh.git
    branch: release-0.11.1
  dest:
    url: https://github.com/red-hat-data-services/modelmesh.git
    branch: main
- name: modelmesh-runtime-adapter
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/modelmesh-runtime-adapter.git
    branch: release-0.11.1
  dest:
    url: https://github.com/red-hat-data-services/modelmesh-runtime-adapter.git
    branch: main
- name: data-science-pipelines-tekton
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/data-science-pipelines-tekton.git
    branch: master
  dest:
    url: https://github.com/red-hat-data-services/data-science-pipelines-tekton.git
    branch: master
- name: data-science-pipelines
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/data-science-pipelines.git
    branch: master
  dest:
    url: https://github.com/red-hat-data-services/data-science-pipelines.git
    branch: master
- name: data-science-pipelines-operator
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/data-science-pipelines-operator.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/data-science-pipelines-operator.git
    branch: main
- name: trustyai-explainability
  automerge: 'no'
  src:
    url: https://github.com/trustyai-explainability/trustyai-explainability.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/trustyai-explainability.git
    branch: main
- name: trustyai-service-operator
  automerge: 'no'
  src:
    url: https://github.com/trustyai-explainability/trustyai-service-operator.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/trustyai-service-operator.git
    branch: main
- name: codeflare-operator
  automerge: 'no'
  src:
    url: https://github.com/opendatahub-io/codeflare-operator.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/codeflare-operator.git
    branch: main
- name: distributed-workloads
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/distributed-workloads.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/distributed-workloads.git
    branch: main
  ignore: codeflare-stack/base/params.env
- name: kuberay
  automerge: 'no'
  src:
    url: https://github.com/opendatahub-io/kuberay.git
    branch: master
  dest:
    url: https://github.com/red-hat-data-services/kuberay.git
    branch: master
- name: text-generation-inference
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/text-generation-inference.git
    branch: release
  dest:
    url: https://github.com/red-hat-data-services/text-generation-inference.git
    branch: main
- name: caikit-tgis-serving
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/caikit-tgis-serving.git
    branch: release
  dest:
    url: https://github.com/red-hat-data-services/caikit-tgis-serving.git
    branch: main
- name: caikit
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/caikit.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/caikit.git
    branch: main
- name: caikit-nlp
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/caikit-nlp.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/caikit-nlp.git
    branch: main
- name: caikit-tgis-backend
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/caikit-tgis-backend.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/caikit-tgis-backend.git
    branch: main
- name: model-registry
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/model-registry.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/model-registry.git
    branch: main
- name: model-registry-operator
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/model-registry-operator.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/model-registry-operator.git
    branch: main
- name: kserve
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/kserve.git
    branch: release-v0.11.1
  dest:
    url: https://github.com/red-hat-data-services/kserve.git
    branch: master
  ignore: config/overlays/odh/params.env
- name: rhods-operator
  automerge: 'no'
  src:
    url: https://github.com/opendatahub-io/opendatahub-operator.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/rhods-operator.git
    branch: main
- name: openvino_model_server
  automerge: 'no'
  src:
    url: https://github.com/opendatahub-io/openvino_model_server.git
    branch: 2023.1-release
  dest:
    url: https://github.com/red-hat-data-services/openvino_model_server.git
    branch: 2023.1-release
- name: fms-hf-tuning
  automerge: 'yes'
  src:
    url: https://github.com/foundation-model-stack/fms-hf-tuning.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/fms-hf-tuning.git
    branch: main
