git:
- name: odh-dashboard
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/odh-dashboard.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/odh-dashboard.git
    branch: main
- name: modelmesh-serving
  automerge: 'yes'
  needs: odh-dashboard
  src:
    url: https://github.com/opendatahub-io/modelmesh-serving.git
    branch: release-0.12.0-rc0
  dest:
    url: https://github.com/red-hat-data-services/modelmesh-serving.git
    branch: main