git:
- name: odh-dashboard
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/odh-dashboard.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/odh-dashboard.git
    branch: main
- name: kubeflow
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/kubeflow.git
    branch: v1.9-branch
  dest:
    url: https://github.com/red-hat-data-services/kubeflow.git
    branch: main
- name: modelmesh-serving
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/modelmesh-serving.git
    branch: release-0.12.0-rc0
  dest:
    url: https://github.com/red-hat-data-services/modelmesh-serving.git
    branch: main
- name: odh-model-controller
  automerge: 'yes'
  ignore-files: config/base/params.env 
  src:
    url: https://github.com/opendatahub-io/odh-model-controller.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/odh-model-controller.git
    branch: main
- name: rest-proxy
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/rest-proxy.git
    branch: release-0.12.0-rc0
  dest:
    url: https://github.com/red-hat-data-services/rest-proxy.git
    branch: main
- name: modelmesh
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/modelmesh.git
    branch: release-0.12.0-rc0
  dest:
    url: https://github.com/red-hat-data-services/modelmesh.git
    branch: main
- name: modelmesh-runtime-adapter
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/modelmesh-runtime-adapter.git
    branch: release-0.12.0-rc0
  dest:
    url: https://github.com/red-hat-data-services/modelmesh-runtime-adapter.git
    branch: main
- name: data-science-pipelines-tekton
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/data-science-pipelines-tekton.git
    branch: master
  dest:
    url: https://github.com/red-hat-data-services/data-science-pipelines-tekton.git
    branch: main
- name: data-science-pipelines
  automerge: 'yes'
  ignore-files: .github/renovate.json5
  src:
    url: https://github.com/opendatahub-io/data-science-pipelines.git
    branch: stable
  dest:
    url: https://github.com/red-hat-data-services/data-science-pipelines.git
    branch: main
- name: data-science-pipelines-operator
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/data-science-pipelines-operator.git
    branch: stable
  dest:
    url: https://github.com/red-hat-data-services/data-science-pipelines-operator.git
    branch: main
- name: argo-workflows
  automerge: 'yes'
  ignore-files: renovate.json
  src:
    url: https://github.com/opendatahub-io/argo-workflows.git
    branch: stable
  dest:
    url: https://github.com/red-hat-data-services/argo-workflows.git
    branch: main
- name: ilab-on-ocp
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/ilab-on-ocp.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/ilab-on-ocp.git
    branch: main
- name: trustyai-explainability
  automerge: 'no'
  src:
    url: https://github.com/trustyai-explainability/trustyai-explainability.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/trustyai-explainability.git
    branch: main
- name: trustyai-service-operator
  automerge: 'no'
  src:
    url: https://github.com/trustyai-explainability/trustyai-service-operator.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/trustyai-service-operator.git
    branch: main
- name: codeflare-upstream
  automerge: 'yes'
  ignore-files: .github/workflows/e2e_tests.yaml
  src:
    url: https://github.com/project-codeflare/codeflare-operator.git
    branch: main
  dest:
    url: https://github.com/opendatahub-io/codeflare-operator.git
    branch: main
- name: codeflare-downstream
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/codeflare-operator.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/codeflare-operator.git
    branch: main
- name: distributed-workloads
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/distributed-workloads.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/distributed-workloads.git
    branch: main
  ignore-files: codeflare-stack/base/params.env
- name: kuberay
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/kuberay.git
    branch: dev
  dest:
    url: https://github.com/red-hat-data-services/kuberay.git
    branch: main
- name: kueue
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/kueue.git
    branch: dev
  dest:
    url: https://github.com/red-hat-data-services/kueue.git
    branch: main
- name: training-operator
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/training-operator.git
    branch: dev
  dest:
    url: https://github.com/red-hat-data-services/training-operator.git
    branch: main
- name: text-generation-inference
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/text-generation-inference.git
    branch: release
  dest:
    url: https://github.com/red-hat-data-services/text-generation-inference.git
    branch: main
- name: caikit-tgis-serving
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/caikit-tgis-serving.git
    branch: release
  dest:
    url: https://github.com/red-hat-data-services/caikit-tgis-serving.git
    branch: main
- name: caikit-nlp
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/caikit-nlp.git
    branch: release
  dest:
    url: https://github.com/red-hat-data-services/caikit-nlp.git
    branch: main
- name: model-registry
  automerge: 'no'
  src:
    url: https://github.com/opendatahub-io/model-registry.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/model-registry.git
    branch: main
- name: model-registry-operator
  automerge: 'no'
  src:
    url: https://github.com/opendatahub-io/model-registry-operator.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/model-registry-operator.git
    branch: main
- name: kserve
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/kserve.git
    branch: release-v0.14
  dest:
    url: https://github.com/red-hat-data-services/kserve.git
    branch: master
  ignore-files: config/overlays/odh/params.env
- name: rhods-operator
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/opendatahub-operator.git
    branch: rhoai
  dest:
    url: https://github.com/red-hat-data-services/rhods-operator.git
    branch: main
- name: openvino_model_server
  automerge: 'no'
  src:
    url: https://github.com/opendatahub-io/openvino_model_server.git
    branch: 2023.1-release
  dest:
    url: https://github.com/red-hat-data-services/openvino_model_server.git
    branch: 2023.1-release
- name: fms-hf-tuning-dev
  automerge: 'yes'
  src:
    url: https://github.com/foundation-model-stack/fms-hf-tuning.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/fms-hf-tuning.git
    branch: main
- name: fms-hf-tuning-release
  automerge: 'yes'
  src:
    url: https://github.com/foundation-model-stack/fms-hf-tuning.git
    branch: release
  dest:
    url: https://github.com/red-hat-data-services/fms-hf-tuning.git
    branch: release
- name: vllm
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/vllm.git
    branch: release
  dest:
    url: https://github.com/red-hat-data-services/vllm.git
    branch: main
- name: vllm-gaudi
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/vllm-gaudi.git
    branch: release
  dest:
    url: https://github.com/red-hat-data-services/vllm-gaudi.git
    branch: main
- name: lm-evaluation-harness
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/lm-evaluation-harness.git
    branch: release-0.4.5
  dest:
    url: https://github.com/red-hat-data-services/lm-evaluation-harness.git
    branch: main
