git:
- name: odh-dashboard
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/odh-dashboard.git
    branch: main
  dest:
    url: https://github.com/red-hat-data-services/odh-dashboard.git
    branch: main
- name: codeflare-upstream
  automerge: 'yes'
  src:
    url: https://github.com/project-codeflare/codeflare-operator.git
    branch: main
  dest:
    url: https://github.com/opendatahub-io/codeflare-operator.git
    branch: dchouras-main
- name: codeflare-downstream
  automerge: 'yes'
  src:
    url: https://github.com/opendatahub-io/codeflare-operator.git
    branch: dchouras-main
  dest:
    url: https://github.com/red-hat-data-services/codeflare-operator.git
    branch: dchouras-main