name: Jira Metrics Tool

on:
  schedule:           
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-metrics-tool:
    runs-on: ubuntu-latest

    env:
      SMARTSHEET_ACCESS_TOKEN: ${{ secrets.SMARTSHEET_ACCESS_TOKEN }}
      BUILD_SHEET_ID: ${{ secrets.BUILD_SHEET_ID }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install smartsheet-python-sdk jira 

    - name: Run the Python script
      run: |
        cd utils/auto-label-nightly
        python auto_label.py
