name: Create Snapshots and Run Conforma Validation

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        description: |
          Full RHOAI version number X.Y.Z 
          or quay URI 
          or blank to use contents of src/config/releases.yaml

env:
  GITHUB_ORG: red-hat-data-services
  SOURCE_MAP: "src/config/releases.yaml"


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.extract.outputs.versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract all versions
        id: extract
        run: |
          if [[ "${{ github.event_name  }}" != "workflow_dispatch" || "${{github.event.inputs.version}}" == "" ]]
          then
            versions=$(yq -o json $SOURCE_MAP | jq --compact-output '.versions_to_snapshot')
          else
            echo "${{ github.event.inputs }}"
            versions="[ \"${{ github.event.inputs.version }}\" ]"
          fi
          echo "versions=$versions"
          echo "versions=$versions" >> $GITHUB_OUTPUT
  trigger-nightly:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        version: ${{ fromJSON(needs.setup.outputs.versions) }}
    steps:
      - name: Generate github-app token
        id: app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.RHDS_DEVOPS_APP_ID }}
          private_key: ${{ secrets.RHDS_DEVOPS_APP_PRIVATE_KEY }}
      - name: clone repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITHUB_ORG }}/conforma-reporter
          token: ${{ steps.app-token.outputs.token }}
      - name: update conforma-reporter
        run: |
          pwd
          ls
          epoch=$(date +%s)
          update="${{ matrix.version }} $epoch"
          echo $update > ./params
          git config --global user.name "rhods-devops-app[bot]"
          git config --global user.email "323671+rhods-devops-app[bot]@users.noreply.github.com"
          git commit -am "Update params to $update"
          git push
