name: Verify Nudges

on:
  schedule:
    - cron: '30 2 * * *'  # Runs at 9 AM IST (2:30 AM UTC)
  workflow_dispatch:
    inputs:
      rhoai-releases:
        description: 'Use commas to specify multiple RHOAI releases. Leave empty to verify all active releases.'
        required: false

jobs:
  verify-nudges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'  # Specify the Python version you need

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies from Pipfile.lock
        run: cd utils/verify-nudge && pipenv install --ignore-pipfile

      - name: Verify Nudges
        env:
          SLACK_WEBHOOK: ${{ secrets.RHOAI_DEVOPS_SLACK_WEBHOOK }}
        run: |
          cd utils/verify-nudge
          if [ -n "${{ github.event.inputs.rhoai-releases }}" ]; then
            pipenv run python main.py --releases=${{ github.event.inputs.rhoai-releases }}
          else
            pipenv run python main.py
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            utils/verify-nudge/downloads

      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: ':red-warning: Nudge Verification Failed!'
          SLACK_WEBHOOK: ${{ secrets.RHOAI_DEVOPS_SLACK_WEBHOOK }}